# netlify.toml

[[redirects]]
  from = "/naver/rss"
  to = "/.netlify/functions/rss"
  status = 200

# [추가됨] 중계자 주소 연결
[[redirects]]
  from = "/go"
  to = "/.netlify/functions/go"
  status = 200
